name: Compile Docker Images

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: servers.web.tr:5002
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: servers.web.tr:5002/pub-server
          tags: |
            type=sha
            type=raw,value=latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.sha=sha-${{ steps.vars.outputs.sha_short }}
            org.opencontainers.image.created=${{ steps.date.outputs.date }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Send webhook
        run: |
          curl --insecure -X POST https://portainer.smart-host.com.tr/api/stacks/webhooks/${{ secrets.webhook }}?SHA=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
